version: "3.7"
services:
  bot:
    image: greboid/irc
    volumes:
      - data:/data
    networks:
      - rpc
    environment:
      CHANNEL: "#test"
      SERVER: "irc.example.tld:6697"
      TLS: "true"
      NICK: "ExampleBot"
      PLUGINS: "github=vz5Czm7s"
  github:
    image: greboid/irc-git
    networks:
      - rpc
    environment:
      RPC_HOST: "bot"
      RPC_TOKEN: "vz5Czm7s"
      CHANNEL: "#test"
networks:
  rpc:
volumes:
  data: