version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - data:/data
    environment:
      CHANNEL: "#test"
      SERVER: "irc.example.tld:6697"
      TLS: "true"
      NICK: "ExampleBot"
      WEB_PORT: "8080"
      PLUGINS: "test=TESTTOKEN"
  testplugin:
    build:
      context: .
      dockerfile: Dockerfile.testplugin
    environment:
      RPC_HOST: "bot"
      RPC_TOKEN: "TESTTOKEN"
      CHANNEL: "#test"
    links:
      - bot
volumes:
  data: